### ISSUE TITLE
「トリミング」に関する報告

### ISSUE THREAD

**Issue by keisaito-mx1** [dninomiya/flock-examples#4]
url:
https://examples.flock.codes/crop

報告内容:
背景画像の選択がPCからだとY軸の移動、スマホからだとX軸の移動になる
PR出したかったのですが、みてもらえますかね？

**Comment by nino-cast** [comment]
@keisaito-mx1 
SP対応がそもそも未着手だったため対応しました ✅

**Comment by keisaito-mx1** [comment]
@nino-cast 
すいません。ちょっと誤解のある質問の仕方でしたね。
クロップすることができない領域があるという意味でした。
PCならY軸の方向にした背景画像を動かせないので、左右の領域をクロップすることができないようになっています。

Twitterのアイコンを変更する時のような挙動で言うと、
縦長の画像はY軸だけの移動でクロップする、横長の画像はX軸の移動でクロップするようなイメージでした

**Comment by dninomiya** [comment]
@keisaito-mx1 
なるほど、、。色々いじってみたところこのライブラリだと実現無理そうなので以下で試してみます。
https://github.com/ValentinH/react-easy-crop

**Comment by dninomiya** [comment]
@keisaito-mx1 
別ライブラリ等試してみましたが最終的に最もシンプルかつTwitter風に近づけると現状の挙動に落ち着きました。
デモだとそもそものキャンバスが横長なので黒い余白が目立ったり、極端に縦長の画像を入れるとトリミングを引きで行うことになるなどの違和感はありますが実際の利用シーンではキャンバスのアスペクト比を最終形態に寄せると思うのと、アバター画像選択に極端な縦長をセットするケースもレアだと思うので現状が個人的な最適解になります。

**Comment by keisaito-mx1** [comment]
@dninomiya 
お忙しい中対応ありがとうござます！こんな挙動を想定していました！ありがとうございました！
